
export const FETCH_BANK_DATA = 'FETCH_BANK_DATA';
export const FETCH_BANK_DATA_FULFILLED = 'FETCH_BANK_DATA_FULFILLED';
export const SELECTED_BANK_DATA = 'SELECTED_BANK_DATA';

export const FETCH_BANK_BALANCE = 'FETCH_BANK_BALANCE';
export const FETCH_BANK_BALANCE_FULFILLED = 'FETCH_BANK_BALANCE_FULFILLED';
